### PR TITLE
Bengali Translation Added

### PR DESCRIPTION
**Pull request by BinTofajjal**

### CODE REVIEW

**Comment by bacloud23** [comment]
great addition. Thanks a lot @BinTofajjal  !

**Comment by bacloud23** [comment]
is `বাংলা` the right way to translate the language `bangali` ?
thanks

**Comment by BinTofajjal** [comment]
> is `বাংলা` the right way to translate the language `bangali` ?
> 
> thanks

Yeah!

**Comment by BinTofajjal** [comment]
> is `বাংলা` the right way to translate the language `bangali` ?
> 
> thanks

If you mean it by language name then It's Bengali not Bangali!

And if you just translate `বাংলা` as a word then it's ‘Bangla’

[Here's wiki](https://en.m.wikipedia.org/wiki/Bengali_language)

**Pull request merged**
